import fs from 'fs';

// All new keys for Login, Register, ForgotPassword, ResetPassword,
// EligibilityCheck, Schemes, Farmers, History, Settings, Dashboard
const newEnglishKeys = {
  // ── Login Page ──
  "login_title": "Welcome Back",
  "login_subtitle": "Sign in to Niti-Setu Engine",
  "login_email": "Email Address",
  "login_email_ph": "Enter your email",
  "login_password": "Password",
  "login_password_ph": "Enter your password",
  "login_authenticating": "Authenticating...",
  "login_forgot": "Forgot your password?",
  "login_no_account": "Don't have an account?",
  "login_or": "OR",
  "login_success": "Login Successful",
  "login_welcome_back": "Welcome back to Niti-Setu",
  "login_auth_failed": "Authentication Failed",
  "login_system_error": "An unexpected error occurred during login.",
  "login_google_success": "Authenticated via Google",
  "login_google_failed": "Google Login Failed",
  "login_google_failed_desc": "Popup closed or authentication failed",

  // ── Register Page ──
  "reg_title": "Create Account",
  "reg_subtitle": "Join the Niti-Setu platform",
  "reg_name": "Full Name",
  "reg_name_ph": "Enter your name",
  "reg_btn": "Create Account",
  "reg_btn_loading": "Creating Account...",
  "reg_or": "OR",
  "reg_have_account": "Already have an account?",
  "reg_signin_link": "Sign In",
  "reg_invalid_password": "Password must be at least 6 characters",
  "reg_success": "Registration Successful",
  "reg_welcome": "Welcome to Niti-Setu",
  "reg_failed": "Registration Failed",
  "reg_system_error": "An unexpected error occurred during registration.",
  "reg_google_failed": "Google Registration Failed",

  // ── Forgot Password Page ──
  "fp_back_login": "Back to Login",
  "fp_title": "Reset",
  "fp_title_accent": "Password",
  "fp_subtitle": "Enter your registered email address. We will generate a secure reset link to get you back into your account.",
  "fp_email_label": "Email Address",
  "fp_btn_send": "Send Reset Link",
  "fp_toast_sent": "Email Sent",
  "fp_toast_sent_desc": "If an account exists, a reset link was generated.",
  "fp_toast_failed": "Reset Failed",
  "fp_mvp_title": "MVP Magic Reset Link",
  "fp_mvp_desc": "In a production app, this would be emailed to you securely. Click the link below to bypass and reset your password instantly!",
  "fp_btn_reset_now": "Reset My Password Now",

  // ── Reset Password Page ──
  "rp_title": "Create New",
  "rp_title_accent": "Password",
  "rp_subtitle": "Your new password must be at least 8 characters long and contain numbers and symbols.",
  "rp_new_password": "New Password",
  "rp_new_password_ph": "Enter new password",
  "rp_confirm_password": "Confirm Password",
  "rp_confirm_password_ph": "Confirm new password",
  "rp_btn_update": "Update Password",
  "rp_mismatch": "Passwords do not match",
  "rp_success_title": "Password Reset Successfully!",
  "rp_success_desc": "Redirecting you to login...",
  "rp_toast_success": "Password has been reset.",
  "rp_toast_failed": "Invalid or expired token",

  // ── EligibilityCheck: VoiceInput ──
  "vi_title": "Voice Input",
  "vi_subtitle": "Describe your farm details by speaking",
  "vi_example": "I am Ramesh from Maharashtra, I have 2 acres of wheat land...",
  "vi_processing": "Processing...",
  "vi_stop": "Stop Recording",
  "vi_start": "Start Recording",
  "vi_listening": "Listening...",
  "vi_transcript": "Transcript",
  "vi_ai_powered": "AI Powered",
  "vi_toast_success": "Voice Processed",
  "vi_toast_success_desc": "Extracted farmer profile from audio source",
  "vi_toast_failed": "Voice Processing Failed",

  // ── EligibilityCheck: ProfileForm ──
  "pf_title": "Farmer Profile",
  "pf_btn": "Check Eligibility",
  "pf_btn_loading": "Analyzing...",
  "cm_state": "State",
  "cm_search": "Select state",
  "cm_district": "District",
  "cm_district_ph": "Select district",
  "cm_land": "Land (acres)",
  "cm_crop": "Crop Type",
  "cm_category": "Social Category",
  "cm_general": "General",
  "cm_obc": "OBC",
  "cm_scst": "SC/ST",
  "cm_ews": "EWS",
  "cm_minority": "Minority",
  "cm_income": "Annual Income (₹)",
  "cm_age": "Age",
  "cm_has_irrigation": "Has Irrigation",
  "cm_cancel": "Cancel",

  // ── EligibilityCheck: ProofCard ──
  "pc_eligible": "Eligible",
  "pc_not_eligible": "Not Eligible",
  "pc_confidence": "Confidence",
  "pc_download_pdf": "Download PDF",
  "pc_exporting": "Exporting...",
  "pc_ai_analysis": "AI Analysis",
  "pc_stop_audio": "Stop Audio",
  "pc_listen": "Listen",
  "pc_benefit_amount": "BENEFIT AMOUNT",
  "pc_required_docs": "Required Documents",
  "pc_items": "items",
  "pc_next_steps": "Next Steps (How to Apply)",
  "pc_why_rejected": "Why was this profile rejected?",
  "pc_scheme_requirement": "Scheme Requirement",
  "pc_your_profile": "Your Profile",
  "pc_doc_source": "Official Document Source",
  "pc_view_document": "View Document",
  "pc_visit_portal": "Visit Official Portal",
  "pc_alt_schemes": "Alternative Schemes You Might Qualify For",
  "pc_high_match": "High Match",
  "pc_potential_match": "Potential Match",
  "pc_potential_benefit": "Potential Benefit",
  "pc_looking_alt": "Looking for alternatives?",
  "pc_alt_desc": "Try modifying your profile parameters if you believe there was an error, or run a Simultaneous Check against all available schemes from the dropdown above.",
  "pc_processed_in": "Processed in",
  "pc_chunks_analyzed": "embedded chunks",
  "pc_scheme_x_of_y": "SCHEME",
  "pc_of": "OF",

  // ── EligibilityCheck: Main ──
  "ec_title": "Eligibility Check",
  "ec_subtitle": "AI-powered scheme eligibility analysis",
  "ec_select_scheme": "Select Government Scheme",
  "ec_choose_scheme": "— Choose a scheme —",
  "ec_all_schemes": "Check All Schemes Simultaneously",
  "ec_scan_results": "Scan Results",
  "ec_schemes_analyzed": "schemes analyzed",

  // ── Schemes Page ──
  "sh_title": "Scheme Knowledge Base",
  "sh_subtitle": "Manage uploaded government scheme documents",
  "sh_add_new": "Add New Scheme",
  "sh_empty": "No schemes uploaded yet",
  "sh_upload_desc": "Upload scheme PDFs to build the knowledge base",
  "sh_upload_pdf": "Upload Scheme PDF",
  "sh_name": "Scheme Name",
  "sh_name_ph": "e.g. PM-KISAN Samman Nidhi",
  "sh_desc": "Description",
  "sh_desc_ph": "Brief description",
  "sh_tbl_category": "Category",
  "sh_cat_income": "Income Support",
  "sh_cat_infra": "Infrastructure",
  "sh_cat_energy": "Energy",
  "sh_cat_other": "Other",
  "sh_file": "PDF Document",
  "sh_file_select": "Click to select PDF file",
  "sh_btn_upload": "Upload & Process",
  "sh_btn_uploading": "Processing PDF...",
  "sh_tbl_chunks": "Chunks",
  "sh_tbl_version": "VERSION",
  "sh_tbl_status": "Status",
  "sh_active": "Active",
  "sh_delete": "Delete",
  "sh_govt_scheme_doc": "Government scheme document",

  // ── Farmers Page ──
  "fm_title": "Farmer Profiles",
  "fm_subtitle": "Registered farmer profiles and their details",
  "fm_search_ph": "Search farmer by name, state...",
  "fm_empty": "No farmer profiles found",
  "fm_unknown": "Unknown Farmer",
  "fm_yrs": "yrs",
  "fm_acres": "acres",

  // ── History Page ──
  "hs_title": "Eligibility History",
  "hs_subtitle": "Track all past eligibility checks and results",
  "hs_tbl_farmer": "Select Farmer Profile",
  "hs_empty": "No profiles created yet. Run an eligibility check to begin.",
  "hs_eligible": "Eligible",
  "hs_not_eligible": "Not Eligible",
  "hs_reason": "REASON",
  "hs_citation": "CITATION",
  "hs_benefit": "Benefit",
  "hs_delete_record": "Delete Record",
  "hs_delete_profile": "Delete Profile & History",
  "hs_run_new_check": "Run New Check for this Profile",
  "hs_no_checks": "No eligibility checks yet",
  "hs_no_checks_desc": "Run your first eligibility check from the Check page",

  // ── Settings Page ──
  "st_title": "Account Settings",
  "st_subtitle": "Update your profile information and security preferences",
  "st_profile_info": "Profile Information",
  "st_full_name": "Full Name",
  "st_email": "Email Address",
  "st_save": "Save Changes",
  "st_saving": "Saving...",
  "st_change_password": "Change Password",
  "st_current_password": "Current Password",
  "st_new_password": "New Password",
  "st_confirm_password": "Confirm New Password",
  "st_update_password": "Update Password",
  "st_updating": "Updating...",

  // ── Dashboard ──
  "db_title": "Dashboard",
  "db_subtitle": "Analytics overview of your scheme eligibility engine",
  "db_total_checks": "Total Checks",
  "db_eligible_rate": "Eligible Rate",
  "db_total_farmers": "Total Farmers",
  "db_schemes_active": "Schemes Active",
  "db_recent_checks": "Recent Eligibility Checks",
  "db_view_all": "View All History",
  "db_no_checks": "No recent checks",
  "db_scheme_distribution": "Scheme Distribution",
  "db_category_breakdown": "Category Breakdown",

  // ── Common / Toast ──
  "toast_system_error": "System Error",
  "toast_missing_scheme": "Missing Scheme",
  "toast_missing_scheme_desc": "Please select a scheme from the dropdown first",
  "toast_limit_reached": "Limit Reached",
  "toast_profile_update": "Profile Update",
  "toast_ai_scanning": "AI Scanning",
  "toast_check_complete": "Check Complete",
  "toast_analysis_failed": "Analysis Failed",
  "toast_generating_pdf": "Generating PDF",
  "toast_download_complete": "Download Complete",
  "toast_export_failed": "Export Failed",
  "toast_scheme_deleted": "Scheme Deleted",
  "toast_deletion_failed": "Deletion Failed",
  "toast_profile_deleted": "Profile Deleted",
  "toast_record_deleted": "Record Deleted"
};

// Hindi translations
const newHindiKeys = {
  "login_title": "वापस स्वागत है",
  "login_subtitle": "Niti-Setu इंजन में साइन इन करें",
  "login_email": "ईमेल पता",
  "login_email_ph": "अपना ईमेल दर्ज करें",
  "login_password": "पासवर्ड",
  "login_password_ph": "अपना पासवर्ड दर्ज करें",
  "login_authenticating": "प्रमाणित कर रहे हैं...",
  "login_forgot": "पासवर्ड भूल गए?",
  "login_no_account": "खाता नहीं है?",
  "login_or": "या",
  "login_success": "लॉगिन सफल",
  "login_welcome_back": "Niti-Setu में वापस स्वागत है",
  "login_auth_failed": "प्रमाणीकरण विफल",
  "login_system_error": "लॉगिन के दौरान अप्रत्याशित त्रुटि हुई।",
  "login_google_success": "Google के माध्यम से प्रमाणित",
  "login_google_failed": "Google लॉगिन विफल",
  "login_google_failed_desc": "पॉपअप बंद या प्रमाणीकरण विफल",

  "reg_title": "खाता बनाएं",
  "reg_subtitle": "Niti-Setu प्लेटफ़ॉर्म से जुड़ें",
  "reg_name": "पूरा नाम",
  "reg_name_ph": "अपना नाम दर्ज करें",
  "reg_btn": "खाता बनाएं",
  "reg_btn_loading": "खाता बना रहे हैं...",
  "reg_or": "या",
  "reg_have_account": "पहले से खाता है?",
  "reg_signin_link": "साइन इन करें",
  "reg_invalid_password": "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए",
  "reg_success": "पंजीकरण सफल",
  "reg_welcome": "Niti-Setu में स्वागत है",
  "reg_failed": "पंजीकरण विफल",
  "reg_system_error": "पंजीकरण के दौरान अप्रत्याशित त्रुटि।",
  "reg_google_failed": "Google पंजीकरण विफल",

  "fp_back_login": "लॉगिन पर वापस जाएं",
  "fp_title": "रीसेट",
  "fp_title_accent": "पासवर्ड",
  "fp_subtitle": "अपना पंजीकृत ईमेल पता दर्ज करें। हम आपके खाते में वापस लाने के लिए एक सुरक्षित रीसेट लिंक बनाएंगे।",
  "fp_email_label": "ईमेल पता",
  "fp_btn_send": "रीसेट लिंक भेजें",
  "fp_toast_sent": "ईमेल भेजा गया",
  "fp_toast_sent_desc": "यदि कोई खाता मौजूद है, तो रीसेट लिंक जनरेट किया गया।",
  "fp_toast_failed": "रीसेट विफल",
  "fp_mvp_title": "MVP मैजिक रीसेट लिंक",
  "fp_mvp_desc": "प्रोडक्शन ऐप में, यह आपको सुरक्षित रूप से ईमेल किया जाएगा। तुरंत अपना पासवर्ड रीसेट करने के लिए नीचे दिए गए लिंक पर क्लिक करें!",
  "fp_btn_reset_now": "अभी मेरा पासवर्ड रीसेट करें",

  "rp_title": "नया बनाएं",
  "rp_title_accent": "पासवर्ड",
  "rp_subtitle": "आपका नया पासवर्ड कम से कम 8 अक्षरों का होना चाहिए और इसमें संख्या और प्रतीक होने चाहिए।",
  "rp_new_password": "नया पासवर्ड",
  "rp_new_password_ph": "नया पासवर्ड दर्ज करें",
  "rp_confirm_password": "पासवर्ड की पुष्टि करें",
  "rp_confirm_password_ph": "नए पासवर्ड की पुष्टि करें",
  "rp_btn_update": "पासवर्ड अपडेट करें",
  "rp_mismatch": "पासवर्ड मेल नहीं खाते",
  "rp_success_title": "पासवर्ड सफलतापूर्वक रीसेट!",
  "rp_success_desc": "लॉगिन पर रीडायरेक्ट कर रहे हैं...",
  "rp_toast_success": "पासवर्ड रीसेट हो गया है।",
  "rp_toast_failed": "अमान्य या समय-सीमित टोकन",

  "vi_title": "आवाज़ इनपुट",
  "vi_subtitle": "बोलकर अपने खेत का विवरण बताएं",
  "vi_example": "मैं महाराष्ट्र से रमेश हूं, मेरे पास 2 एकड़ गेहूं की भूमि है...",
  "vi_processing": "प्रोसेसिंग...",
  "vi_stop": "रिकॉर्डिंग बंद करें",
  "vi_start": "रिकॉर्डिंग शुरू करें",
  "vi_listening": "सुन रहे हैं...",
  "vi_transcript": "ट्रांसक्रिप्ट",
  "vi_ai_powered": "AI संचालित",
  "vi_toast_success": "आवाज़ प्रोसेस हुई",
  "vi_toast_success_desc": "ऑडियो स्रोत से किसान प्रोफ़ाइल निकाली",
  "vi_toast_failed": "आवाज़ प्रोसेसिंग विफल",

  "pf_title": "किसान प्रोफ़ाइल",
  "pf_btn": "पात्रता जांचें",
  "pf_btn_loading": "विश्लेषण कर रहे हैं...",
  "cm_state": "राज्य",
  "cm_search": "राज्य चुनें",
  "cm_district": "जिला",
  "cm_district_ph": "जिला चुनें",
  "cm_land": "भूमि (एकड़)",
  "cm_crop": "फसल का प्रकार",
  "cm_category": "सामाजिक श्रेणी",
  "cm_general": "सामान्य",
  "cm_obc": "OBC",
  "cm_scst": "SC/ST",
  "cm_ews": "EWS",
  "cm_minority": "अल्पसंख्यक",
  "cm_income": "वार्षिक आय (₹)",
  "cm_age": "आयु",
  "cm_has_irrigation": "सिंचाई उपलब्ध है",
  "cm_cancel": "रद्द करें",

  "pc_eligible": "पात्र",
  "pc_not_eligible": "अपात्र",
  "pc_confidence": "विश्वास",
  "pc_download_pdf": "PDF डाउनलोड करें",
  "pc_exporting": "एक्सपोर्ट हो रहा है...",
  "pc_ai_analysis": "AI विश्लेषण",
  "pc_stop_audio": "ऑडियो बंद करें",
  "pc_listen": "सुनें",
  "pc_benefit_amount": "लाभ राशि",
  "pc_required_docs": "आवश्यक दस्तावेज़",
  "pc_items": "आइटम",
  "pc_next_steps": "अगले कदम (कैसे आवेदन करें)",
  "pc_why_rejected": "इस प्रोफ़ाइल को क्यों अस्वीकार किया गया?",
  "pc_scheme_requirement": "योजना की आवश्यकता",
  "pc_your_profile": "आपकी प्रोफ़ाइल",
  "pc_doc_source": "आधिकारिक दस्तावेज़ स्रोत",
  "pc_view_document": "दस्तावेज़ देखें",
  "pc_visit_portal": "आधिकारिक पोर्टल देखें",
  "pc_alt_schemes": "वैकल्पिक योजनाएं जिनके लिए आप पात्र हो सकते हैं",
  "pc_high_match": "उच्च मिलान",
  "pc_potential_match": "संभावित मिलान",
  "pc_potential_benefit": "संभावित लाभ",
  "pc_looking_alt": "विकल्प खोज रहे हैं?",
  "pc_alt_desc": "यदि आपको लगता है कि कोई त्रुटि हुई है, तो अपनी प्रोफ़ाइल को संशोधित करें, या ड्रॉपडाउन से सभी योजनाओं की एक साथ जांच करें।",
  "pc_processed_in": "प्रोसेसिंग समय",
  "pc_chunks_analyzed": "एम्बेडेड चंक विश्लेषित",
  "pc_scheme_x_of_y": "योजना",
  "pc_of": "में से",

  "ec_title": "पात्रता जांच",
  "ec_subtitle": "AI-संचालित योजना पात्रता विश्लेषण",
  "ec_select_scheme": "सरकारी योजना चुनें",
  "ec_choose_scheme": "— एक योजना चुनें —",
  "ec_all_schemes": "सभी योजनाओं की एक साथ जांच करें",
  "ec_scan_results": "स्कैन परिणाम",
  "ec_schemes_analyzed": "योजनाएं विश्लेषित",

  "sh_title": "योजना ज्ञान आधार",
  "sh_subtitle": "अपलोड की गई सरकारी योजना दस्तावेजों का प्रबंधन करें",
  "sh_add_new": "नई योजना जोड़ें",
  "sh_empty": "अभी तक कोई योजना अपलोड नहीं हुई",
  "sh_upload_desc": "ज्ञान आधार बनाने के लिए योजना PDF अपलोड करें",
  "sh_upload_pdf": "योजना PDF अपलोड करें",
  "sh_name": "योजना का नाम",
  "sh_name_ph": "उदा. PM-KISAN सम्मान निधि",
  "sh_desc": "विवरण",
  "sh_desc_ph": "संक्षिप्त विवरण",
  "sh_tbl_category": "श्रेणी",
  "sh_cat_income": "आय सहायता",
  "sh_cat_infra": "बुनियादी ढांचा",
  "sh_cat_energy": "ऊर्जा",
  "sh_cat_other": "अन्य",
  "sh_file": "PDF दस्तावेज़",
  "sh_file_select": "PDF फ़ाइल चुनने के लिए क्लिक करें",
  "sh_btn_upload": "अपलोड और प्रोसेस",
  "sh_btn_uploading": "PDF प्रोसेस हो रहा है...",
  "sh_tbl_chunks": "चंक",
  "sh_tbl_version": "संस्करण",
  "sh_tbl_status": "स्थिति",
  "sh_active": "सक्रिय",
  "sh_delete": "हटाएं",
  "sh_govt_scheme_doc": "सरकारी योजना दस्तावेज़",

  "fm_title": "किसान प्रोफ़ाइल",
  "fm_subtitle": "पंजीकृत किसान प्रोफ़ाइल और उनका विवरण",
  "fm_search_ph": "नाम, राज्य से किसान खोजें...",
  "fm_empty": "कोई किसान प्रोफ़ाइल नहीं मिली",
  "fm_unknown": "अज्ञात किसान",
  "fm_yrs": "वर्ष",
  "fm_acres": "एकड़",

  "hs_title": "पात्रता इतिहास",
  "hs_subtitle": "सभी पिछली पात्रता जांचों और परिणामों को ट्रैक करें",
  "hs_tbl_farmer": "किसान प्रोफ़ाइल चुनें",
  "hs_empty": "अभी तक कोई प्रोफ़ाइल नहीं बनी। शुरू करने के लिए पात्रता जांच चलाएं।",
  "hs_eligible": "पात्र",
  "hs_not_eligible": "अपात्र",
  "hs_reason": "कारण",
  "hs_citation": "उद्धरण",
  "hs_benefit": "लाभ",
  "hs_delete_record": "रिकॉर्ड हटाएं",
  "hs_delete_profile": "प्रोफ़ाइल और इतिहास हटाएं",
  "hs_run_new_check": "इस प्रोफ़ाइल के लिए नई जांच करें",
  "hs_no_checks": "अभी तक कोई पात्रता जांच नहीं",
  "hs_no_checks_desc": "जांच पेज से अपनी पहली पात्रता जांच चलाएं",

  "st_title": "खाता सेटिंग्स",
  "st_subtitle": "अपनी प्रोफ़ाइल जानकारी और सुरक्षा प्राथमिकताएं अपडेट करें",
  "st_profile_info": "प्रोफ़ाइल जानकारी",
  "st_full_name": "पूरा नाम",
  "st_email": "ईमेल पता",
  "st_save": "बदलाव सहेजें",
  "st_saving": "सहेज रहे हैं...",
  "st_change_password": "पासवर्ड बदलें",
  "st_current_password": "वर्तमान पासवर्ड",
  "st_new_password": "नया पासवर्ड",
  "st_confirm_password": "नए पासवर्ड की पुष्टि करें",
  "st_update_password": "पासवर्ड अपडेट करें",
  "st_updating": "अपडेट हो रहा है...",

  "db_title": "डैशबोर्ड",
  "db_subtitle": "आपके योजना पात्रता इंजन का विश्लेषण अवलोकन",
  "db_total_checks": "कुल जांचें",
  "db_eligible_rate": "पात्रता दर",
  "db_total_farmers": "कुल किसान",
  "db_schemes_active": "सक्रिय योजनाएं",
  "db_recent_checks": "हाल की पात्रता जांचें",
  "db_view_all": "सभी इतिहास देखें",
  "db_no_checks": "कोई हाल की जांच नहीं",
  "db_scheme_distribution": "योजना वितरण",
  "db_category_breakdown": "श्रेणी विश्लेषण",

  "toast_system_error": "सिस्टम त्रुटि",
  "toast_missing_scheme": "योजना गायब है",
  "toast_missing_scheme_desc": "कृपया पहले ड्रॉपडाउन से एक योजना चुनें",
  "toast_limit_reached": "सीमा पूरी",
  "toast_profile_update": "प्रोफ़ाइल अपडेट",
  "toast_ai_scanning": "AI स्कैनिंग",
  "toast_check_complete": "जांच पूर्ण",
  "toast_analysis_failed": "विश्लेषण विफल",
  "toast_generating_pdf": "PDF बना रहे हैं",
  "toast_download_complete": "डाउनलोड पूर्ण",
  "toast_export_failed": "एक्सपोर्ट विफल",
  "toast_scheme_deleted": "योजना हटाई गई",
  "toast_deletion_failed": "हटाना विफल",
  "toast_profile_deleted": "प्रोफ़ाइल हटाई गई",
  "toast_record_deleted": "रिकॉर्ड हटाया गया"
};

let content = fs.readFileSync('src/i18n.js', 'utf8');

// 1. Add to English section - find last lp key before closing
const enEntries = Object.entries(newEnglishKeys)
  .map(([k, v]) => `      "${k}": "${v.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`)
  .join(',\n');

content = content.replace(
  /("lp_footer_made": "Made with ❤️ in Kolhapur, Maharashtra\.")\n(\s*}\r?\n\s*},)/,
  `$1,\n${enEntries}\n$2`
);

// 2. Add to Hindi section - find last Hindi lp key
const hiEntries = Object.entries(newHindiKeys)
  .map(([k, v]) => `      "${k}": "${v.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`)
  .join(',\n');

// Find the last Hindi lp_footer_made key
content = content.replace(
  /("lp_footer_made": "[^"]*")\n(\s*}\r?\n\s*},\r?\n\s*mr:)/,
  `$1,\n${hiEntries}\n$2`
);

fs.writeFileSync('src/i18n.js', content, 'utf8');
console.log(`✅ Added ${Object.keys(newEnglishKeys).length} English keys`);
console.log(`✅ Added ${Object.keys(newHindiKeys).length} Hindi keys`);
